# Generated by Django 3.2.7 on 2021-09-29 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='oauthgiteeuser',
            table='meiduo_oauth_gitee',
        ),
    ]
